### ISSUE TITLE
是不是不支持Typescript？

### ISSUE THREAD

**Issue by codeWinson** [eggjs/egg-knex#19]
配置部分：
${app_root}/config/plugin.ts:
import { EggPlugin } from 'egg';
const plugin: EggPlugin = {
  knex: {
    enable: true,
    package: 'egg-knex'
  }
};
export default plugin;
${app_root}/config/config.${env}.ts:
import { DefaultConfig } from './config.default';
export default () => {
  const config: DefaultConfig = {};
  config.knex = {
    client: {
      dialect: 'mysql',
      connection: {
        host: '127.0.0.1',
        port: '3306',
        user: 'root',
        password: '111111',
        database: 'life'
      },
      pool: { min: 0, max: 5 },
      acquireConnectionTimeout: 30000,
    },
    app: true,
    agent: true,
  }
  return config;
};
结果：
![image](https://user-images.githubusercontent.com/32981007/43447320-d59a7356-94dd-11e8-8947-6daf5d349ad4.png)
在Application对象上获取不到knex？

**Comment by sunfuze** [comment]
目前不支持，后面加上index.d.ts。目前你可以在extend/context.ts，加上

```typescript
{
  get knex() {
    return (this.app as any).knex
  }
}
```

通过 ctx 去获取knex 实例。不过这种方式还是会有一些问题。
