### ISSUE TITLE
请问在多数据库实例下如何设置acquireConnectionTimeout？

### ISSUE THREAD

**Issue by Wand3ring** [eggjs/egg-knex#23]
在多数据库实例下，acquireConnectionTimeout如何设置？
如下为配置文件：
// Edit config.default.js
exports.knex = {
    default: {
      acquireConnectionTimeout: 30000,
    },
    app: true,
    agent: false,
  };

这样设置后，acquireConnectionTimeout的时间依旧没有生效，是否为我配置错误？感谢！

**Comment by Wand3ring** [comment]
粗暴的解决方式：
在node_moduel中将knex默认的15000值调整即可。
不过该方法并不优雅。

**Comment by sunfuze** [comment]
@weiyibo-passion 写到 default 里没有问题啊，你可以在通过 `ctx.app.knex.get('${dbname}').client.config` 拿到配置。我试过了是没有问题的。

**Comment by weiyibo-passion** [comment]
Hi，感谢您的回复。我后面试了一下，config里面可以拿到配置。只不过mssql没能正常启用对应的配置信息。

**Comment by Wand3ring** [comment]
> @weiyibo-passion 写到 default 里没有问题啊，你可以在通过 `ctx.app.knex.get('${dbname}').client.config` 拿到配置。我试过了是没有问题的。
Hi，感谢您的回复。我后面试了一下，config里面可以拿到配置。只不过mssql没能正确获取对应的配置文件信息。
