### ISSUE TITLE
TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full

### ISSUE THREAD

**Issue by anUniqueBoy** [eggjs/egg-knex#29]
TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

**Comment by anUniqueBoy** [comment]
How to solve it

**Comment by sunfuze** [comment]
> TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

Can you provide more using code?
