### ISSUE TITLE
自定义logger输出

### ISSUE THREAD

**Issue by callmez** [eggjs/egg-knex#5]
现在的日志是在coreLogger
在开发的时候会想输出在console里, 
能不能像egg-sequelize一样可以自定义日志输出.  默认也是输出到app.logger. 这样方便调试. 不需要去文件里查看.

谢谢!

**Comment by sunfuze** [comment]
2.0.2 版本会把日志输出到 `logs/egg-knex.log`，同时会在console输出。你也可以自定义 custom logger：

```js config.js
exports.customLogger = {
   knex: {
      file: path.join(app.root, 'logs/egg-knex.log')  // 可以自行在 config.${env}.js 中修改
    }
}

```

@okoala 发下版本

**Comment by okoala** [comment]
done

**Comment by okoala** [comment]
@sunfuze  发你的 npm 账号我，我添加你权限

**Comment by sunfuze** [comment]
@okoala 账号应该就是 sunfuze

**Comment by okoala** [comment]
好了
