### ISSUE TITLE
何时可以发布新版本？

### ISSUE THREAD

**Issue by rockcookies** [eggjs/egg-knex#9]
看到源码已经修复了低版本 mysql  不支持 explain 语句的BUG，何时才能发布？

**Comment by atian25** [comment]
这个库是 @sunfuze 维护的。

**Comment by atian25** [comment]
BTW... @sunfuze 看你的 commit message 都不符合规范...

**Comment by yolopunk** [comment]
@Rockcookies  发布的2.0.8 这个版本，已经修复了呀

**Comment by rockcookies** [comment]
@yolopunk  不好意思，淘宝NPM镜像刚更新了，现在看到 2.0.8 版本了。https://npm.taobao.org/sync/egg-knex#logid=3679107

**Comment by sunfuze** [comment]
@atian25 确实~
